nelmio_api_doc:
    documentation:
        info:
            title: Symfony Api Doc
            description: Vejá como é simples documentar minha api
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!_error/.*|api/doc$)
            # - ^/(?!/doc$|!/_error/*$) # Accepts routes under /api except /api/doc
